package com.ning.infrastructure.utils;

import cn.hutool.core.util.IdUtil;
import com.ning.domain.service.IDService;
import com.ning.infrastructure.common.leaf.common.Result;
import com.ning.infrastructure.common.leaf.common.Status;
import lombok.extern.slf4j.Slf4j;
import org.springframework.util.Assert;

@Slf4j
public class IDUtils {

    private static final IDService iDService;

    static {
        iDService = SpringUtil.getBean(IDService.class);
        Assert.notNull(iDService, "IDService can`t be null.");
    }

    public static Long getId() {
        Result result = iDService.id();
        if (result.getStatus() != Status.SUCCESS) {
            log.error("Id generated by leaf failure, use snowflake id.");
            return IdUtil.getSnowflakeNextId();
        }
        return result.getId();
    }

}
