server:
  port: 8080

spring:
  application:
    name: exam-ning-gateway
  config:
    import: optional:nacos:${spring.application.name}.yml
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # 服务注册中心
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        # 认证服务
        - id: exam-ning-auth
          uri: lb://exam-ning-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        # 考试服务
        - id: exam-ning-system-exam
          uri: lb://exam-ning-system-exam
          predicates:
            - Path=/exam/**
        # 用户服务
        - id: exam-ning-system-user
          uri: lb://exam-ning-system-user
          predicates:
            - Path=/system/**

logging:
  config: classpath:log4j2-spring.xml
  file:
    path: ${LOG_FILE_PATH:E:\tmp\mnt\logs\exam\gateway}
    max-size: 100 MB
    max-history: 30
#  level:
#    root: ${LOG_LEVEL_ROOT:INFO}
