server:
  port: 9527

spring:
  application:
    name: exam-ning-auth
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # 服务注册中心
  redis:
    host: 127.0.0.1
    port: 6379
    database: 15

feign:
  client:
    config:
      default:
        connectTimeout: 30000
        readTimeout: 30000
  hystrix:
    enabled: false

